spring.application.name=bank-management-system

server.port=8080

spring.datasource.url=jdbc:postgresql://dpg-xxxxx.singapore-postgres.render.com:5432/<dbname>
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect